name: sim_env
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.0.8
  - matplotlib=3.6.2
  - numpy=1.24.1
  - pandas=1.5.2
  - pip=21.0.1
  - python=3.8.12
  - scipy=1.10.0
  - simpy=4.0.1
  - joblib=1.2.0
  - pip:
    - streamlit
    - streamlit-bokeh-events==0.1.2
    - seaborn==0.12.2